exercicio 19 sem teste
estudos-db/Bruno-Baptista pull request #2
Opened 2023-03-20 16:17 UTC by brn29

finalizado exercício 19 em java, mas ainda sem testes em junit

2023-03-21 18:58 UTC, ralfdw3 requested changes
O enunciado do exercício está um pouco vago, porém por ser um exercício de orientação a objetos, seria interessante aparecer no código. Pode fazer uma classe de contato e outras que extendem essa, como contato de celular, contato de email, contato de telefone fixo, ou algo deste gênero, apenas para praticar a POO.

2023-03-21 18:58 UTC, ralfdw3 commented on lista-de-exercicios-java/src/main/java/org/example/exercicio19/Agenda.java
No método removerContato e listarContatos tem um if contatos.size() que é desnecessário em ambos os casos.

2023-03-21 19:14 UTC, brn29 commented on lista-de-exercicios-java/src/main/java/org/example/exercicio19/Agenda.java
removi o "if contatos.size()" do método "removerContato", onde realmente ficou desnecessário, mas acho interessante manter no método "listarContatos" para informar quando a lista estiver vazia. E mudei o if para "if(contatos.size() > 0)", que faz mais sentido.

2023-03-22 13:37 UTC, ralfdw3 requested changes
No exercício 16 não está sendo utilizado POO. Sugiro fazer 2 classes que extendem livro (digital e fisico) implementando alguns métodos específicos e herdando coisas mais básicas da classe pai. 

No exercício 19 utilizar enum para categoria.

2023-03-23 14:21 UTC, ralfdw3 requested changes

2023-03-23 14:21 UTC, ralfdw3 commented on lista-de-exercicios-java/src/main/java/org/example/exercicio19/Agenda.java
if(contato.getCategoria().toString().equals(categoria.toString())) -> Você está pegando os 2 enums, transformando para String e comparando os dois, porém você poderia comparar diretamente os 2 enums, ficaria mais claro o código.

Outro ponto importante, você está utilizando void no retorno em todos os métodos, será que isso está correto? Se tem um método listarContatosPorCategoria, será que o retorno é void? Ou será que o retorno seria uma lista de contatos, por exemplo?

2023-03-24 15:11 UTC, brn29 commented on lista-de-exercicios-java/src/main/java/org/example/exercicio19/Agenda.java
O retorno em void na maioria é temporário enquanto ainda não estou escrevendo os testes, pretendo alterá-los quando for escrever os testes.

2023-03-29 14:15 UTC, closed without merging